### ISSUE TITLE
Add Ability To Load Model Parameters From Memory

### ISSUE THREAD

**Issue by tk4218** [deepakkumar1984/MxNet.Sharp#6]
I need to be able to store symbol and parameter files into a database and then load them into a model after retrieving them from the database. Currently, I can store the symbol file as a JSON string and load it using `Symbol.LoadJSON()`, however I cannot do this with the .params file. 

Could we add the ability to load the parameter file from a buffer? I was able to do this by using `MXNDArrayLoadFromBuffer()`. This works just like `MXNDArrayLoad()`, but instead of loading from a file it will load from the in-memory bytes.

**Comment by deepakkumar1984** [comment]
I think should be easy to add. I will lokk into it.
